/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MobileFrame.java
 *
 * Created on Nov 1, 2010, 2:43:21 PM
 */

package jadecity.frames.agentsFrame;

import jadecity.classes.agentsClasses.MobileAgent;

/**
 *
 * @author SONY
 */
public class MobileFrame extends javax.swing.JFrame {

    private MobileAgent agent;

    /** Creates new form MobileFrame */
    public MobileFrame(MobileAgent ag)
    {
        initComponents();
        agent=ag;
        NameLabel.setText(ag.getName());
        this.setTitle(ag.getLocalName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xLocLabel = new javax.swing.JLabel();
        yLocLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xDestLabel = new javax.swing.JLabel();
        yDestLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        totalDistanceLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        destCityLabel = new javax.swing.JLabel();
        sourceCityLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        currentSpeedLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 18));
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Mobile Agent Frame");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadecity/images/ex.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        NameLabel.setForeground(new java.awt.Color(51, 0, 102));
        NameLabel.setText("MobileAgent123");

        jLabel2.setText("Location :");

        xLocLabel.setText("xLocLabel");

        yLocLabel.setText("yLocLabel");

        jLabel5.setText("Destination :");

        xDestLabel.setText("xDestLabel");

        yDestLabel.setText("yDestLabel");

        jLabel8.setText("Default Speed :");

        speedLabel.setText("speedLabel");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadecity/images/kdmconfig.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadecity/images/remote.png"))); // NOI18N

        jLabel9.setText("Area Name :");

        areaLabel.setText("areaLabel");

        totalDistanceLabel.setText("totalDistanceLabel");

        jLabel10.setText("Total Distance :");

        destCityLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        destCityLabel.setText("A");

        sourceCityLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        sourceCityLabel.setText("A");

        jLabel6.setText("First City :");

        jLabel7.setText("Destination City :");

        currentSpeedLabel.setText("currentSpeedLabel");

        jLabel11.setText("Current Speed :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sourceCityLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(39, 39, 39)
                                                .addComponent(xLocLabel))
                                            .addComponent(yLocLabel))
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(currentSpeedLabel)
                                            .addComponent(speedLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(areaLabel)
                                    .addComponent(totalDistanceLabel)
                                    .addComponent(jButton1))
                                .addGap(24, 24, 24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(destCityLabel))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xDestLabel)
                                    .addComponent(yDestLabel))))
                        .addGap(54, 54, 54)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameLabel)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sourceCityLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(xLocLabel))
                                .addGap(18, 18, 18)
                                .addComponent(yLocLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(speedLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(currentSpeedLabel))))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(areaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(totalDistanceLabel))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xDestLabel)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(yDestLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(destCityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(91, 91, 91))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileFrame(new MobileAgent()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    public javax.swing.JLabel areaLabel;
    public javax.swing.JLabel currentSpeedLabel;
    public javax.swing.JLabel destCityLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel sourceCityLabel;
    public javax.swing.JLabel speedLabel;
    public javax.swing.JLabel totalDistanceLabel;
    public javax.swing.JLabel xDestLabel;
    public javax.swing.JLabel xLocLabel;
    public javax.swing.JLabel yDestLabel;
    public javax.swing.JLabel yLocLabel;
    // End of variables declaration//GEN-END:variables

}
